apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Optional, specify a storage class name
  volumeName: mongo-pv  # Specify the name of the associated PersistentVolume
