apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.3-rc1-jammy
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-volume
          mountPath: /storage/data
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
  volumeClaimTemplates:
  - metadata:
      name: volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi