apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
      - name: client-app
        image: kevinkimanzi4/client:v1.0.0.1
        ports:
        - containerPort: 3000