---
# tasks file for installdocker
- name: Install dependancy.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: yes
         
- name: add docker GPG keys
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
    
- name: Make sure docker is running and will run on booting
  service:
    name: docker
    state: started
    enabled: yes


- name: Install docker compose python package.
  ansible.builtin.pip:
    name: docker-compose

- name: Install docker module for python
  pip:
    name: docker